name: core-build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    name: ubuntu-24.04-clang-18
    steps:
      - name: Checkout AzerothCore
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: azerothcore/azerothcore-wotlk
          ref: master
          submodules: recursive
          persist-credentials: false

      - name: Checkout module
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: modules/mod-starting-pet
          submodules: recursive
          persist-credentials: false

      - name: Build and validate module
        uses: ./.github/actions/linux-build
        with:
          CC: clang-18
          CXX: clang++-18
          modules: true
          pch: false
          maxerrors: 1
          keepgoing: false
